-- 创建高亮公司表
CREATE TABLE IF NOT EXISTS highlight_companies (
    id SERIAL PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_highlight_companies_category ON highlight_companies(category);
CREATE INDEX IF NOT EXISTS idx_highlight_companies_company_name ON highlight_companies(company_name);

-- 创建更新触发器
CREATE OR REPLACE FUNCTION update_highlight_companies_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_highlight_companies_timestamp_trigger
    BEFORE UPDATE ON highlight_companies
    FOR EACH ROW
    EXECUTE FUNCTION update_highlight_companies_timestamp();

-- 添加约束，确保类别是有效的
ALTER TABLE highlight_companies
ADD CONSTRAINT highlight_companies_category_chk
CHECK (category IN ('金融量化', 'web3', '互联网', 'AI', '传统金融'));

-- 插入初始数据（从 companyCategories.ts 导入）
INSERT INTO highlight_companies (company_name, category) VALUES
-- 金融量化
('幻方量化', '金融量化'),
('九坤投资', '金融量化'),
('灵均投资', '金融量化'),
('明汯投资', '金融量化'),
('诚奇资产', '金融量化'),
('金锝资产', '金融量化'),
('衍复投资', '金融量化'),
('佳期投资', '金融量化'),
('宽德投资', '金融量化'),
('天演资本', '金融量化'),
('稳博投资', '金融量化'),
('启林投资', '金融量化'),
('世纪前沿资产', '金融量化'),
('黑翼资产', '金融量化'),
('金戈量锐', '金融量化'),
('茂源量化', '金融量化'),
('思勰投资', '金融量化'),
('因诺资产', '金融量化'),
('艾方资产', '金融量化'),
('博普', '金融量化'),
('进化论资产', '金融量化'),
('宽投资产', '金融量化'),
('龙旗科技', '金融量化'),
('鸣石基金', '金融量化'),
('念空念觉', '金融量化'),
('千象投资', '金融量化'),
('千宜投资', '金融量化'),
('乾象投资', '金融量化'),
('锐天投资', '金融量化'),
('信弘天禾', '金融量化'),
('展弘投资', '金融量化'),
('致诚卓远', '金融量化'),
('卓识基金', '金融量化'),
('白鹭资管', '金融量化'),
('呈瑞投资', '金融量化'),
('国恩资本', '金融量化'),
('涵德投资', '金融量化'),
('赫富投资', '金融量化'),
('均成资产', '金融量化'),
('凯纳资本', '金融量化'),
('洛书投资', '金融量化'),
('蒙玺投资', '金融量化'),
('平方和投资', '金融量化'),
('申毅投资', '金融量化'),
('盛冠达', '金融量化'),
('思晔投资', '金融量化'),
('天算量化', '金融量化'),
('象限投资', '金融量化'),
('衍盛资产', '金融量化'),
('仲阳天王星', '金融量化'),
('Hudson River Trading', '金融量化'),
('Jump', '金融量化'),
('Virtu', '金融量化'),
('Tower Research', '金融量化'),
('Jane Street', '金融量化'),
('Citadel Securities', '金融量化'),
('IMC', '金融量化'),
('Optiver', '金融量化'),
('Akuna', '金融量化'),
('DRW', '金融量化'),
('SIG', '金融量化'),
('Five Rings', '金融量化'),
('Two Sigma', '金融量化'),
('DE Shaw', '金融量化'),
('PDT', '金融量化'),
('RenTec', '金融量化'),
('文艺复兴', '金融量化'),
('Millennium', '金融量化'),
('Point72', '金融量化'),
('Citadel', '金融量化'),
('Balyasny', '金融量化'),
('Exodus Point', '金融量化'),
('World Quant', '金融量化'),
('AQR', '金融量化'),
('BlackRock', '金融量化'),
('贝莱德', '金融量化'),
('MAN Numeric', '金融量化'),
('英仕曼', '金融量化'),
('Bridgewater', '金融量化'),
('桥水基金', '金融量化'),
('高塔', '金融量化'),
('time research', '金融量化'),
('kronos research', '金融量化'),
('LTP', '金融量化'),
('cyberX', '金融量化'),
('wintermute', '金融量化'),
('presto', '金融量化'),
('nayt', '金融量化'),
('LUX', '金融量化'),
('简街资本', '金融量化'),
('城堡证券', '金融量化'),
('摩根士丹利', '金融量化'),
('高盛', '金融量化'),
('摩根大通', '金融量化'),
('花旗', '金融量化'),
('德意志银行', '金融量化'),
('巴克莱银行', '金融量化'),
('瑞银集团', '金融量化'),
('汇丰', '金融量化')
ON CONFLICT (company_name) DO NOTHING;

-- web3
INSERT INTO highlight_companies (company_name, category) VALUES
('币安', 'web3'),
('Binance', 'web3'),
('Coinbase', 'web3'),
('Bybit', 'web3'),
('OKX', 'web3'),
('Kraken', 'web3'),
('KuCoin', 'web3'),
('Gate.io', 'web3'),
('HTX', 'web3'),
('MEXC', 'web3'),
('Bitget', 'web3'),
('Crypto.com', 'web3'),
('BingX', 'web3'),
('Upbit', 'web3'),
('Bithumb', 'web3'),
('XT.COM', 'web3'),
('Phemex', 'web3'),
('BitMEX', 'web3'),
('Pionex', 'web3'),
('HashKey', 'web3'),
('Deribit', 'web3'),
('FTX', 'web3'),
('欧易', 'web3'),
('派网', 'web3'),
('火币', 'web3'),
('Huobi', 'web3'),
('Matrixport', 'web3'),
('比特大陆', 'web3'),
('Amber', 'web3'),
('DWF', 'web3'),
('imToken', 'web3'),
('MetaMask', 'web3'),
('Trust Wallet', 'web3'),
('Phantom', 'web3'),
('Coinbase Wallet', 'web3'),
('Ethereum', 'web3'),
('Bitcoin', 'web3'),
('Solana', 'web3'),
('BNB Chain', 'web3'),
('Polygon', 'web3'),
('Arbitrum', 'web3'),
('Optimism', 'web3'),
('Avalanche', 'web3'),
('Cardano', 'web3'),
('Polkadot', 'web3'),
('Chainlink', 'web3'),
('Uniswap', 'web3'),
('PancakeSwap', 'web3'),
('SushiSwap', 'web3'),
('Curve', 'web3'),
('Aave', 'web3'),
('Compound', 'web3'),
('Maker', 'web3'),
('Synthetix', 'web3'),
('Yearn', 'web3'),
('1inch', 'web3'),
('dYdX', 'web3'),
('GMX', 'web3'),
('Osmosis', 'web3'),
('THORChain', 'web3'),
('Kujira', 'web3'),
('Terra', 'web3'),
('Cosmos', 'web3'),
('Injective', 'web3'),
('Sei', 'web3'),
('Celestia', 'web3'),
('Aptos', 'web3'),
('Sui', 'web3'),
('Near', 'web3'),
('Flow', 'web3'),
('Tezos', 'web3'),
('Algorand', 'web3'),
('Hedera', 'web3'),
('Internet Computer', 'web3'),
('Filecoin', 'web3'),
('Theta', 'web3'),
('VeChain', 'web3'),
('Chiliz', 'web3'),
('Enjin', 'web3'),
('Decentraland', 'web3'),
('The Sandbox', 'web3'),
('Axie Infinity', 'web3'),
('Gala', 'web3'),
('Illuvium', 'web3'),
('Star Atlas', 'web3')
ON CONFLICT (company_name) DO NOTHING;

-- 互联网
INSERT INTO highlight_companies (company_name, category) VALUES
('腾讯', '互联网'),
('Tencent', '互联网'),
('阿里巴巴', '互联网'),
('Alibaba', '互联网'),
('百度', '互联网'),
('Baidu', '互联网'),
('京东', '互联网'),
('JD', '互联网'),
('美团', '互联网'),
('Meituan', '互联网'),
('字节跳动', '互联网'),
('ByteDance', '互联网'),
('TikTok', '互联网'),
('抖音', '互联网'),
('网易', '互联网'),
('NetEase', '互联网'),
('拼多多', '互联网'),
('Pinduoduo', '互联网'),
('小红书', '互联网'),
('Xiaohongshu', '互联网'),
('得物', '互联网'),
('滴滴出行', '互联网'),
('Didi', '互联网'),
('哔哩哔哩', '互联网'),
('Bilibili', '互联网'),
('快手', '互联网'),
('Kuaishou', '互联网'),
('微博', '互联网'),
('Weibo', '互联网'),
('知乎', '互联网'),
('Zhihu', '互联网'),
('谷歌', '互联网'),
('Google', '互联网'),
('苹果', '互联网'),
('Apple', '互联网'),
('微软', '互联网'),
('Microsoft', '互联网'),
('亚马逊', '互联网'),
('Amazon', '互联网'),
('Facebook', '互联网'),
('Meta', '互联网'),
('Netflix', '互联网'),
('Uber', '互联网'),
('Airbnb', '互联网'),
('Twitter', '互联网'),
('LinkedIn', '互联网'),
('Snapchat', '互联网'),
('Pinterest', '互联网'),
('Reddit', '互联网'),
('Discord', '互联网'),
('Zoom', '互联网'),
('Slack', '互联网'),
('Spotify', '互联网'),
('PayPal', '互联网'),
('eBay', '互联网'),
('Salesforce', '互联网'),
('Adobe', '互联网'),
('Oracle', '互联网'),
('IBM', '互联网'),
('Intel', '互联网'),
('NVIDIA', '互联网'),
('AMD', '互联网'),
('Qualcomm', '互联网'),
('Tesla', '互联网')
ON CONFLICT (company_name) DO NOTHING;

-- AI
INSERT INTO highlight_companies (company_name, category) VALUES
('OpenAI', 'AI'),
('Anthropic', 'AI'),
('智谱', 'AI'),
('月之暗面', 'AI'),
('Moonshot', 'AI'),
('百川智能', 'AI'),
('商汤', 'AI'),
('SenseTime', 'AI'),
('旷视', 'AI'),
('Face++', 'AI'),
('依图', 'AI'),
('云从', 'AI'),
('第四范式', 'AI'),
('明略', 'AI'),
('海康威视', 'AI'),
('大华', 'AI'),
('科大讯飞', 'AI'),
('iFLYTEK', 'AI'),
('搜狗', 'AI'),
('Sogou', 'AI'),
('出门问问', 'AI'),
('思必驰', 'AI'),
('云知声', 'AI'),
('竹间智能', 'AI'),
('追一科技', 'AI'),
('达观数据', 'AI'),
('澜舟科技', 'AI'),
('循环智能', 'AI'),
('崧智智能', 'AI'),
('深兰科技', 'AI'),
('云天励飞', 'AI'),
('格灵深瞳', 'AI'),
('奇点云', 'AI'),
('第六感', 'AI'),
('图普科技', 'AI'),
('码隆科技', 'AI'),
('深醒科技', 'AI'),
('云拿科技', 'AI'),
('影谱科技', 'AI'),
('Video++', 'AI'),
('阅面科技', 'AI'),
('银河水滴', 'AI'),
('眼神科技', 'AI'),
('的卢深视', 'AI'),
('豆包', 'AI'),
('通义千问', 'AI'),
('文心一言', 'AI'),
('kimi', 'AI'),
('讯飞星火', 'AI'),
('紫东太初', 'AI'),
('盘古', 'AI'),
('悟道', 'AI'),
('源1.0', 'AI'),
('鹏程·盘古', 'AI'),
('华为', 'AI'),
('Huawei', 'AI'),
('小米', 'AI'),
('Xiaomi', 'AI'),
('OPPO', 'AI'),
('vivo', 'AI'),
('一加', 'AI'),
('OnePlus', 'AI'),
('阿里云', 'AI')
ON CONFLICT (company_name) DO NOTHING;

-- 传统金融
INSERT INTO highlight_companies (company_name, category) VALUES
('中国银行', '传统金融'),
('工商银行', '传统金融'),
('建设银行', '传统金融'),
('农业银行', '传统金融'),
('交通银行', '传统金融'),
('招商银行', '传统金融'),
('浦发银行', '传统金融'),
('中信银行', '传统金融'),
('民生银行', '传统金融'),
('光大银行', '传统金融'),
('华夏银行', '传统金融'),
('平安银行', '传统金融'),
('兴业银行', '传统金融'),
('邮储银行', '传统金融'),
('中国人寿', '传统金融'),
('平安保险', '传统金融'),
('太平洋保险', '传统金融'),
('新华保险', '传统金融'),
('泰康保险', '传统金融'),
('人保财险', '传统金融'),
('太平保险', '传统金融'),
('阳光保险', '传统金融'),
('天安保险', '传统金融'),
('华泰保险', '传统金融'),
('中信证券', '传统金融'),
('海通证券', '传统金融'),
('广发证券', '传统金融'),
('国泰君安', '传统金融'),
('华泰证券', '传统金融'),
('招商证券', '传统金融'),
('中金公司', '传统金融'),
('申万宏源', '传统金融'),
('兴业证券', '传统金融'),
('银河证券', '传统金融'),
('国信证券', '传统金融'),
('方正证券', '传统金融'),
('长江证券', '传统金融'),
('东方证券', '传统金融'),
('光大证券', '传统金融'),
('中投证券', '传统金融'),
('华西证券', '传统金融'),
('西南证券', '传统金融'),
('国元证券', '传统金融'),
('东北证券', '传统金融'),
('太平洋证券', '传统金融'),
('华安证券', '传统金融'),
('长城证券', '传统金融'),
('东莞证券', '传统金融'),
('东方财富', '传统金融'),
('同花顺', '传统金融'),
('大智慧', '传统金融'),
('恒生电子', '传统金融'),
('金证股份', '传统金融'),
('顶点软件', '传统金融'),
('赢时胜', '传统金融'),
('长亮科技', '传统金融')
ON CONFLICT (company_name) DO NOTHING;

